/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ClaimVision AI - Multimodal insurance evidence verification API
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface ApiError {
  error: string;
}

export interface ImageAnalysis {
  image_id: string;
  image_path: string;
  visible_issue: string;
  object_part: string;
  severity: string;
  visible_damage: boolean;
  image_quality: string;
  wrong_object: boolean;
  explanation: string;
  /** @nullable */
  blur_score?: number | null;
  is_blurry: boolean;
}

export interface Claim {
  id: string;
  user_id: string;
  image_paths: string[];
  user_claim: string;
  claim_object: string;
  /** @nullable */
  evidence_standard_met?: boolean | null;
  /** @nullable */
  evidence_standard_met_reason?: string | null;
  risk_flags: string[];
  /** @nullable */
  issue_type?: string | null;
  /** @nullable */
  object_part?: string | null;
  /** @nullable */
  claim_status?: string | null;
  /** @nullable */
  claim_status_justification?: string | null;
  supporting_image_ids: string[];
  /** @nullable */
  valid_image?: boolean | null;
  /** @nullable */
  severity?: string | null;
  processed: boolean;
  /** @nullable */
  image_analyses?: ImageAnalysis[] | null;
  /** @nullable */
  processing_time_seconds?: number | null;
  /** @nullable */
  token_usage?: number | null;
}

export interface DatasetUpload {
  /** Dataset name: 'sample' or 'test' */
  dataset?: string;
}

export interface UploadResult {
  success: boolean;
  message: string;
  claims_count: number;
  files_uploaded: string[];
}

export interface ProcessInput {
  /** Dataset to process: 'sample' or 'test' */
  dataset: string;
  /**
     * Maximum number of claims to process (null = all)
     * @nullable
     */
  max_claims?: number | null;
}

export interface ProcessResult {
  success: boolean;
  message: string;
  total_claims: number;
  processed_claims: number;
  /** @nullable */
  output_file?: string | null;
  runtime_seconds: number;
  total_tokens: number;
}

export interface ProcessingStatus {
  is_processing: boolean;
  /** @nullable */
  current_claim?: number | null;
  /** @nullable */
  total_claims?: number | null;
  /** @nullable */
  progress_percent?: number | null;
  /** @nullable */
  current_user_id?: string | null;
  /** @nullable */
  status_message?: string | null;
  /** @nullable */
  started_at?: string | null;
  /** @nullable */
  elapsed_seconds?: number | null;
}

export type AnalyticsRiskFlagFrequency = {[key: string]: number};

export type AnalyticsObjectTypeDistribution = {[key: string]: number};

export interface StatusDistribution {
  supported: number;
  contradicted: number;
  not_enough_information: number;
}

export interface SeverityDistribution {
  none: number;
  low: number;
  medium: number;
  high: number;
  unknown: number;
}

export interface Analytics {
  total_claims: number;
  status_distribution: StatusDistribution;
  severity_distribution: SeverityDistribution;
  risk_flag_frequency: AnalyticsRiskFlagFrequency;
  object_type_distribution: AnalyticsObjectTypeDistribution;
  evidence_standard_rate: number;
  /** @nullable */
  avg_processing_time?: number | null;
  total_tokens: number;
  estimated_cost_usd: number;
}

export interface DatasetInfo {
  has_sample_claims: boolean;
  has_test_claims: boolean;
  has_user_history: boolean;
  has_evidence_requirements: boolean;
  /** @nullable */
  sample_claims_count?: number | null;
  /** @nullable */
  test_claims_count?: number | null;
  has_sample_images: boolean;
  has_test_images: boolean;
  processed_claims_count: number;
}

export type GetClaimsParams = {
status?: string;
severity?: string;
object_type?: string;
};

