/**
 * Generated by orval v8.9.1 🍺
 * Do not edit manually.
 * Api
 * ClaimVision AI - Multimodal insurance evidence verification API
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  Analytics,
  ApiError,
  Claim,
  DatasetInfo,
  DatasetUpload,
  GetClaimsParams,
  HealthStatus,
  ProcessInput,
  ProcessResult,
  ProcessingStatus,
  UploadResult
} from './api.schemas';

import { customFetch } from './custom-fetch';
import type { ErrorType , BodyType } from './custom-fetch';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getHealthCheckUrl = () => {




  return `/api/healthz`
}

/**
 * @summary Health check
 */
export const healthCheck = async ( options?: RequestInit): Promise<HealthStatus> => {

  return customFetch<HealthStatus>(getHealthCheckUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getHealthCheckQueryKey = () => {
    return [
    `/api/healthz`
    ] as const;
    }


export const getHealthCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthCheckQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({ signal }) => healthCheck({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthCheck>>>
export type HealthCheckQueryError = ErrorType<unknown>


/**
 * @summary Health check
 */

export function useHealthCheck<TData = Awaited<ReturnType<typeof healthCheck>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthCheck>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetClaimsUrl = (params?: GetClaimsParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : value.toString())
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/claims?${stringifiedParams}` : `/api/claims`
}

/**
 * @summary Get all processed claims
 */
export const getClaims = async (params?: GetClaimsParams, options?: RequestInit): Promise<Claim[]> => {

  return customFetch<Claim[]>(getGetClaimsUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClaimsQueryKey = (params?: GetClaimsParams,) => {
    return [
    `/api/claims`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetClaimsQueryOptions = <TData = Awaited<ReturnType<typeof getClaims>>, TError = ErrorType<unknown>>(params?: GetClaimsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClaims>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClaimsQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClaims>>> = ({ signal }) => getClaims(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClaims>>, TError, TData> & { queryKey: QueryKey }
}

export type GetClaimsQueryResult = NonNullable<Awaited<ReturnType<typeof getClaims>>>
export type GetClaimsQueryError = ErrorType<unknown>


/**
 * @summary Get all processed claims
 */

export function useGetClaims<TData = Awaited<ReturnType<typeof getClaims>>, TError = ErrorType<unknown>>(
 params?: GetClaimsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClaims>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetClaimsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetClaimUrl = (id: string,) => {




  return `/api/claims/${id}`
}

/**
 * @summary Get a single claim by ID
 */
export const getClaim = async (id: string, options?: RequestInit): Promise<Claim> => {

  return customFetch<Claim>(getGetClaimUrl(id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetClaimQueryKey = (id: string,) => {
    return [
    `/api/claims/${id}`
    ] as const;
    }


export const getGetClaimQueryOptions = <TData = Awaited<ReturnType<typeof getClaim>>, TError = ErrorType<ApiError>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClaimQueryKey(id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClaim>>> = ({ signal }) => getClaim(id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData> & { queryKey: QueryKey }
}

export type GetClaimQueryResult = NonNullable<Awaited<ReturnType<typeof getClaim>>>
export type GetClaimQueryError = ErrorType<ApiError>


/**
 * @summary Get a single claim by ID
 */

export function useGetClaim<TData = Awaited<ReturnType<typeof getClaim>>, TError = ErrorType<ApiError>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getClaim>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetClaimQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getUploadDatasetUrl = () => {




  return `/api/upload-dataset`
}

/**
 * @summary Upload CSV dataset files
 */
export const uploadDataset = async (datasetUpload: DatasetUpload, options?: RequestInit): Promise<UploadResult> => {
    const formData = new FormData();
if(datasetUpload.dataset !== undefined) {
 formData.append(`dataset`, datasetUpload.dataset);
 }

  return customFetch<UploadResult>(getUploadDatasetUrl(),
  {
    ...options,
    method: 'POST'
    ,
    body:
      formData,
  }
);}




export const getUploadDatasetMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDataset>>, TError,{data: BodyType<DatasetUpload>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof uploadDataset>>, TError,{data: BodyType<DatasetUpload>}, TContext> => {

const mutationKey = ['uploadDataset'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadDataset>>, {data: BodyType<DatasetUpload>}> = (props) => {
          const {data} = props ?? {};

          return  uploadDataset(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UploadDatasetMutationResult = NonNullable<Awaited<ReturnType<typeof uploadDataset>>>
    export type UploadDatasetMutationBody = BodyType<DatasetUpload>
    export type UploadDatasetMutationError = ErrorType<unknown>

    /**
 * @summary Upload CSV dataset files
 */
export const useUploadDataset = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDataset>>, TError,{data: BodyType<DatasetUpload>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof uploadDataset>>,
        TError,
        {data: BodyType<DatasetUpload>},
        TContext
      > => {
      return useMutation(getUploadDatasetMutationOptions(options));
    }

export const getProcessClaimsUrl = () => {




  return `/api/process-claims`
}

/**
 * @summary Start processing claims with AI vision analysis
 */
export const processClaims = async (processInput: ProcessInput, options?: RequestInit): Promise<ProcessResult> => {

  return customFetch<ProcessResult>(getProcessClaimsUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      processInput,)
  }
);}




export const getProcessClaimsMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processClaims>>, TError,{data: BodyType<ProcessInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
): UseMutationOptions<Awaited<ReturnType<typeof processClaims>>, TError,{data: BodyType<ProcessInput>}, TContext> => {

const mutationKey = ['processClaims'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof processClaims>>, {data: BodyType<ProcessInput>}> = (props) => {
          const {data} = props ?? {};

          return  processClaims(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type ProcessClaimsMutationResult = NonNullable<Awaited<ReturnType<typeof processClaims>>>
    export type ProcessClaimsMutationBody = BodyType<ProcessInput>
    export type ProcessClaimsMutationError = ErrorType<unknown>

    /**
 * @summary Start processing claims with AI vision analysis
 */
export const useProcessClaims = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof processClaims>>, TError,{data: BodyType<ProcessInput>}, TContext>, request?: SecondParameter<typeof customFetch>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof processClaims>>,
        TError,
        {data: BodyType<ProcessInput>},
        TContext
      > => {
      return useMutation(getProcessClaimsMutationOptions(options));
    }

export const getGetProcessingStatusUrl = () => {




  return `/api/processing-status`
}

/**
 * @summary Get current processing job status
 */
export const getProcessingStatus = async ( options?: RequestInit): Promise<ProcessingStatus> => {

  return customFetch<ProcessingStatus>(getGetProcessingStatusUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetProcessingStatusQueryKey = () => {
    return [
    `/api/processing-status`
    ] as const;
    }


export const getGetProcessingStatusQueryOptions = <TData = Awaited<ReturnType<typeof getProcessingStatus>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProcessingStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetProcessingStatusQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getProcessingStatus>>> = ({ signal }) => getProcessingStatus({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getProcessingStatus>>, TError, TData> & { queryKey: QueryKey }
}

export type GetProcessingStatusQueryResult = NonNullable<Awaited<ReturnType<typeof getProcessingStatus>>>
export type GetProcessingStatusQueryError = ErrorType<unknown>


/**
 * @summary Get current processing job status
 */

export function useGetProcessingStatus<TData = Awaited<ReturnType<typeof getProcessingStatus>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getProcessingStatus>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetProcessingStatusQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getDownloadOutputUrl = () => {




  return `/api/download-output`
}

/**
 * @summary Download the generated output.csv
 */
export const downloadOutput = async ( options?: RequestInit): Promise<string> => {

  return customFetch<string>(getDownloadOutputUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getDownloadOutputQueryKey = () => {
    return [
    `/api/download-output`
    ] as const;
    }


export const getDownloadOutputQueryOptions = <TData = Awaited<ReturnType<typeof downloadOutput>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadOutput>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDownloadOutputQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof downloadOutput>>> = ({ signal }) => downloadOutput({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof downloadOutput>>, TError, TData> & { queryKey: QueryKey }
}

export type DownloadOutputQueryResult = NonNullable<Awaited<ReturnType<typeof downloadOutput>>>
export type DownloadOutputQueryError = ErrorType<unknown>


/**
 * @summary Download the generated output.csv
 */

export function useDownloadOutput<TData = Awaited<ReturnType<typeof downloadOutput>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof downloadOutput>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDownloadOutputQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetAnalyticsUrl = () => {




  return `/api/analytics`
}

/**
 * @summary Get analytics and metrics for all processed claims
 */
export const getAnalytics = async ( options?: RequestInit): Promise<Analytics> => {

  return customFetch<Analytics>(getGetAnalyticsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAnalyticsQueryKey = () => {
    return [
    `/api/analytics`
    ] as const;
    }


export const getGetAnalyticsQueryOptions = <TData = Awaited<ReturnType<typeof getAnalytics>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAnalyticsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAnalytics>>> = ({ signal }) => getAnalytics({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAnalyticsQueryResult = NonNullable<Awaited<ReturnType<typeof getAnalytics>>>
export type GetAnalyticsQueryError = ErrorType<unknown>


/**
 * @summary Get analytics and metrics for all processed claims
 */

export function useGetAnalytics<TData = Awaited<ReturnType<typeof getAnalytics>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAnalytics>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAnalyticsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







export const getGetDatasetInfoUrl = () => {




  return `/api/dataset-info`
}

/**
 * @summary Get info about the currently loaded dataset
 */
export const getDatasetInfo = async ( options?: RequestInit): Promise<DatasetInfo> => {

  return customFetch<DatasetInfo>(getGetDatasetInfoUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDatasetInfoQueryKey = () => {
    return [
    `/api/dataset-info`
    ] as const;
    }


export const getGetDatasetInfoQueryOptions = <TData = Awaited<ReturnType<typeof getDatasetInfo>>, TError = ErrorType<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDatasetInfo>>, TError, TData>, request?: SecondParameter<typeof customFetch>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDatasetInfoQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDatasetInfo>>> = ({ signal }) => getDatasetInfo({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDatasetInfo>>, TError, TData> & { queryKey: QueryKey }
}

export type GetDatasetInfoQueryResult = NonNullable<Awaited<ReturnType<typeof getDatasetInfo>>>
export type GetDatasetInfoQueryError = ErrorType<unknown>


/**
 * @summary Get info about the currently loaded dataset
 */

export function useGetDatasetInfo<TData = Awaited<ReturnType<typeof getDatasetInfo>>, TError = ErrorType<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getDatasetInfo>>, TError, TData>, request?: SecondParameter<typeof customFetch>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetDatasetInfoQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}







